// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaffManagementAPI.Repository;

#nullable disable

namespace StaffManagementAPI.Migrations;

[ExcludeFromCodeCoverage]
[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.19")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

        modelBuilder.Entity("StaffManagementAPI.Data.Staff", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                b.Property<DateTime>("Birthday")
                    .HasColumnType("datetime(6)");

                b.Property<string>("FullName")
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<int>("Gender")
                    .HasColumnType("int");

                b.Property<string>("StaffId")
                    .HasMaxLength(8)
                    .HasColumnType("varchar(8)");

                b.HasKey("Id");

                b.HasIndex("StaffId")
                    .IsUnique();

                b.ToTable("Staffs");
            });
#pragma warning restore 612, 618
    }
}
